apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "terminated-pod-cleaner.fullname" . }}
  labels:
    {{- include "terminated-pod-cleaner.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get","list"]
